name: Flutter CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Accept Android SDK Licenses
        run: | 
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk

      - name: Install NDK
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;28.0.12433566"

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Read version from pubspec.yaml
        id: version
        run: |
          version_line=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          version_name=$(echo $version_line | cut -d'+' -f1)
          
          echo "version_name=$version_name" >> $GITHUB_OUTPUT

      - name: Rename APK
        run: |
          APK_NAME="Counter-(${{ steps.version.outputs.version_name }}).apk"
          APK_PATH="build/app/outputs/flutter-apk/$APK_NAME"
          
          # Save environment variables for later steps
          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          
          # Rename the default generated APK
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk "$APK_PATH"

      #  ---------------------- Firebase App Distribution ----------------------

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          serviceCredentialsFileContent: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          testers: ${{ secrets.TESTERS_EMAILS }}
          file: ${{ env.APK_PATH }}
          releaseNotes: "Hi ðŸ‘‹, A new release of the App is ready! Check it out."

      # ---------------------- Hosted download page ----------------------

      - name: Prepare Deployment To Hosted Download Page
        run: |
          mkdir -p surge-deploy
          APK_NAME="${{ env.APK_NAME }}"
          APK_PATH="${{ env.APK_PATH }}"
        
          # Copy APK to deploy folder
          cp "$APK_PATH" surge-deploy/

          # Copy HTML template
          cp template/download.html surge-deploy/index.html

          # Replace placeholder with actual APK name
          sed -i "s/\\$APK_NAME/$APK_NAME/g" surge-deploy/index.html
          # sed -i "s|\\$APK_NAME|$APK_NAME|g" surge-deploy/index.html # If it includes directories (../..).

      - name: Setup Node and Install Surge
        uses: actions/setup-node@v3
        with:
          node-version: '22.18.0'

      - run: npm install --global surge

      - name: Deploy to Surge
        run: surge ./surge-deploy new-app-release.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "New App Release ðŸš€"
          body: |
            Hi ðŸ‘‹,
            A new release of the Counter App is ready!
            You can download it from the link below:

            ðŸ“¦ https://new-app-release.surge.sh

          to: "${{ secrets.TESTERS_EMAILS }}"
          from: "<${{ secrets.EMAIL_USERNAME }}>"